name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  run_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run extraction
        run: python extract.py

      - name: Run transformation
        run: python transform.py

      - name: Run visualization
        run: python visualize.py

      - name: Run benchmarking
        run: python benchmark.py

      - name: Clean and compress data
        run: python clean.py